### ISSUE TITLE
Can not load external class library to main assembly 

### ISSUE THREAD

**Issue by nminhdangit** [yamakadi/clroxide#14]
I am using a Harmony dependency library, which is built as a single DLL in my project. However, when I run it, I always encounter the error: 'Could not invoke method: HRESULT(0x80131604).

**Comment by yamakadi** [comment]
Loading external dependencies is not supported out of the box — at least not always. If the default methods are giving an error, you can try to load external dependencies manually, or use Assembly.Load in dotnet directly instead of the FFI load method.

There’s a good example showing how to load the automation/powershell dependencies here: [examples/powershell_runspace.rs](examples/powershell_runspace.rs)
